### ISSUE TITLE
ROADMAP: Conversations

### ISSUE THREAD

**Issue by etkirsch** [etkirsch/tolmea#25]
- [ ] Sort Conversations by most recent message
  * This means that Conversations need PUT permissions for both Consultants and Users
  * It also means that Conversations must be updated on message addition
- [ ] Contextual rolls based on character stats
  * Need to bring out the rolling stuff into its own service
  * Should properly register stuff like "/roll strength" or "/save strength" or "/roll strength save"
- [ ] Characters need active health and not just current health
- [ ] Expand greatly the DM panel

**Comment by Tyroche** [comment]
Regarding #3:

Would that mean when an episode starts, we should have a page that involved characters can navigate to and see all of those stats?  Like a live view of how the episode is going?

Because I don't think 'live' information like current HP and hit dice available would live with their permanent stats, necessarily.

**Comment by Tyroche** [comment]
Does this mean you envision groups using the site for full sessions, or only for tracking campaigns? :)

**Comment by etkirsch** [comment]
Less so full sessions, but more towards allowing the DM to be able to administer side adventures for the players on off days.

**Comment by Tyroche** [comment]
I'll take a quick shot at #3 then :)

If you keep working and get to that point and want to do it instead, no biggie.  

I'm a bit lazier :)

**Comment by etkirsch** [comment]
Yeah, absolutely go for it. With HD expended that should probably be something like `Character.playableClass[N].spentHitDice` or something, since we already know how many HD they have with the level field.

**Comment by etkirsch** [comment]
I'll put that in its own issue for ya

**Comment by etkirsch** [comment]
Referenced in #26

**Comment by etkirsch** [comment]
Also I think the vitals should be with the character, because certain things might persist from session to session. Not certain the best way to do that though.

**Comment by Tyroche** [comment]
Will we have a separate view for these, or should I just expose them on the character sheet? :)

**Comment by etkirsch** [comment]
I think just expose them on the character sheet. Perhaps in the panels? Maybe like so in the HP Panel:

```
HP:  Cur / Max
HD: [class_1] + [class_2] / [class_1_max] + [class_2_max]
```

?

**Comment by Tyroche** [comment]
Sounds good.  
I'll probably being doing this tomorrow night, I've been tied up today!

**Comment by Tyroche** [comment]
I've got it working, just one question: don't HD differ by class? 

If so, then they need to be displayed apart from each other so they can choose which hit dice to use...

**Comment by etkirsch** [comment]
It does, yep

**Comment by Tyroche** [comment]
Boy oh boy! 8)
